#include "address_map_arm.h"
#include <stdio.h>

void set_A9_IRQ_stack(void);
void config_GIC(void);
void enable_irq(void);
void enable_A9_interrupts(void);
/* key_pressed and pattern is written by an interrupt service routines; we have to
 * declare these as volatile to avoid the compiler caching their values in
 * registers */
volatile int multiplier_interrupt_flag = 0;

/* ********************************************************************************
 * This program demonstrates use of interrupts with C code. 
 
 * Initially the value of the switches is represented on the LEDs
 
********************************************************************************/
int main(void) {
    volatile int *slv_reg0_ptr = (int *)SLV_REG0_ADDR;
    volatile int *slv_reg1_ptr = (int *)SLV_REG1_ADDR;
    volatile int *slv_reg2_ptr = (int *)SLV_REG2_ADDR;
    volatile int *slv_reg3_ptr = (int *)SLV_REG3_ADDR;

    int result, multiplicand, multiplier;
    char continue_flag;

    set_A9_IRQ_stack();      // initialize the stack pointer for IRQ mode
    config_GIC();            // configure the general interrupt controller

    enable_irq();           // enable multiplier interrupts
    enable_A9_interrupts(); // enable interrupts
    
    printf("\nProgram starts...\n");

    do {
    
        // check that there is no pending multiplication (busy output)
        while (*slv_reg3_ptr & (1 << 1));
        
        // activate and deactivate ack signal
        *slv_reg3_ptr |= (1 << 2);  // set ack signal to 1
        *slv_reg3_ptr &= ~(1 << 2); // clear ack signal to 0
        
        // prompt user for multiplicand and multiplier
        printf("Enter the multiplicand: ");
        scanf("%d", &multiplicand);
        printf("Enter the multiplier: ");
        scanf("%d", &multiplier);
        
        *slv_reg0_ptr = multiplicand; // write multiplicand to slv_reg0
        *slv_reg1_ptr = multiplier;   // write multiplier to slv_reg1


        // start multiplication (set start signal to 1)
        *slv_reg3_ptr |= 1;

        // wait for multiplication to complete
        while (!multiplier_interrupt_flag);

        // reset interrupt flag
        multiplier_interrupt_flag = 0;


        // clear start signal
        *slv_reg3_ptr &= ~1;


        // ask if user wants to perform another multiplication
        printf("Do you want to perform another multiplication? (y/n): ");
        scanf(" %c", &continue_flag);  // space before %c to ignore newline characters

    } while (continue_flag == 'y' || continue_flag == 'Y');

    printf("Program ended.\n");
    return 0;
}
/* enable interrupts generated by the multiplier */
void enable_irq()
{
    volatile int * slv_reg3_ptr = (int *)SLV_REG3_ADDR; // pointer to slv_reg3 address

    *slv_reg3_ptr |= (1 << 3); // set bit 3 in slv_reg3 to enable interrupts
}

