#include "address_map_arm.h"
#include <stdio.h>
#define COUNT28_BASE_ADDRESS 0xFF200020

void set_A9_IRQ_stack(void);
void config_GIC(void);
void enable_irq(void);
void enable_A9_interrupts(void);
/* key_pressed and pattern is written by an interrupt service routines; we have to
 * declare these as volatile to avoid the compiler caching their values in
 * registers */
volatile int multiplier_interrupt_flag = 0;

/* ********************************************************************************
 * This program demonstrates use of interrupts with C code. 
 
 * Initially the value of the switches is represented on the LEDs
 
********************************************************************************/
int main(void)
{

    //volatile int *leds = (int *)LEDR_BASE;
    volatile int *count28_enable = (int *)COUNT28_BASE_ADDRESS;

    set_A9_IRQ_stack();      // initialize the stack pointer for IRQ mode
    config_GIC();            // configure the general interrupt controller

    enable_irq();           // enable multiplier interrupts

    enable_A9_interrupts(); // enable interrupts
    
    printf("\nProgram starts...\n");
    
 

    while (1)
    {
    	*count28_enable = key_pressed;      
    }
}

/* enable interrupts generated by the multiplier */
void enable_irq()
{
    volatile int * slv_reg3_ptr = (int *)SLV_REG3_ADDR; // pointer to slv_reg3 address

    *slv_reg3_ptr |= (1 << 3); // set bit 3 in slv_reg3 to enable interrupts
}

